/** JSON Schema for xAI structured outputs. Keep additionalProperties: false. */
export const KIT_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "brandName",
    "tagline",
    "problemHeadline",
    "whyCloseToRevenue",
    "leaks",
    "candidateServices",
    "offer",
    "pitch",
    "stack",
    "pricing",
    "site",
    "prospects",
    "assessmentScript",
    "playbook",
    "nicheAdvice",
  ],
  properties: {
    brandName: { type: "string" },
    tagline: { type: "string" },
    problemHeadline: { type: "string" },
    whyCloseToRevenue: { type: "string" },
    leaks: {
      type: "array",
      minItems: 2,
      maxItems: 5,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "description", "ownerPain", "dollarShape"],
        properties: {
          name: { type: "string" },
          description: { type: "string" },
          ownerPain: { type: "string" },
          dollarShape: { type: "string" },
        },
      },
    },
    candidateServices: {
      type: "array",
      minItems: 5,
      maxItems: 5,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "description", "whyItSells", "selected"],
        properties: {
          name: { type: "string" },
          description: { type: "string" },
          whyItSells: { type: "string" },
          selected: { type: "boolean" },
        },
      },
    },
    offer: {
      type: "object",
      additionalProperties: false,
      required: ["name", "promise", "included", "guarantee", "notIncluded"],
      properties: {
        name: { type: "string" },
        promise: { type: "string" },
        included: { type: "array", items: { type: "string" }, minItems: 5, maxItems: 8 },
        guarantee: { type: "string" },
        notIncluded: { type: "array", items: { type: "string" }, minItems: 3, maxItems: 6 },
      },
    },
    pitch: {
      type: "object",
      additionalProperties: false,
      required: ["oneLiner", "threeSteps", "doorOpener", "objectionHandles"],
      properties: {
        oneLiner: { type: "string" },
        threeSteps: {
          type: "array",
          minItems: 3,
          maxItems: 3,
          items: { type: "string" },
        },
        doorOpener: { type: "string" },
        objectionHandles: {
          type: "array",
          minItems: 4,
          maxItems: 4,
          items: {
            type: "object",
            additionalProperties: false,
            required: ["objection", "reply"],
            properties: {
              objection: { type: "string" },
              reply: { type: "string" },
            },
          },
        },
      },
    },
    stack: {
      type: "object",
      additionalProperties: false,
      required: ["platform", "operatorOwns", "clientOwns", "positioning"],
      properties: {
        platform: { type: "string" },
        operatorOwns: { type: "array", items: { type: "string" }, minItems: 4, maxItems: 8 },
        clientOwns: { type: "array", items: { type: "string" }, minItems: 2, maxItems: 3 },
        positioning: { type: "string" },
      },
    },
    pricing: {
      type: "object",
      additionalProperties: false,
      required: [
        "currency",
        "foundingSetup",
        "foundingMonthly",
        "foundingTerms",
        "laterSetupMin",
        "laterSetupMax",
        "laterMonthlyMin",
        "laterMonthlyMax",
        "whenToRaise",
        "avoid",
      ],
      properties: {
        currency: { type: "string" },
        foundingSetup: { type: "number" },
        foundingMonthly: { type: "number" },
        foundingTerms: { type: "string" },
        laterSetupMin: { type: "number" },
        laterSetupMax: { type: "number" },
        laterMonthlyMin: { type: "number" },
        laterMonthlyMax: { type: "number" },
        whenToRaise: { type: "string" },
        avoid: { type: "string" },
      },
    },
    site: {
      type: "object",
      additionalProperties: false,
      required: [
        "brandName",
        "tagline",
        "hero",
        "subhead",
        "steps",
        "included",
        "cta",
        "footerNote",
      ],
      properties: {
        brandName: { type: "string" },
        tagline: { type: "string" },
        hero: { type: "string" },
        subhead: { type: "string" },
        steps: { type: "array", minItems: 3, maxItems: 3, items: { type: "string" } },
        included: { type: "array", items: { type: "string" }, minItems: 5, maxItems: 8 },
        cta: { type: "string" },
        footerNote: { type: "string" },
      },
    },
    prospects: {
      type: "array",
      minItems: 10,
      maxItems: 10,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "name",
          "niche",
          "city",
          "rating",
          "reviewCount",
          "leakSignals",
          "whyWalkIn",
          "mapsQuery",
          "routeOrder",
        ],
        properties: {
          name: { type: "string" },
          niche: { type: "string" },
          city: { type: "string" },
          rating: { type: "number" },
          reviewCount: { type: "number" },
          leakSignals: { type: "array", items: { type: "string" }, minItems: 2, maxItems: 3 },
          whyWalkIn: { type: "string" },
          mapsQuery: { type: "string" },
          routeOrder: { type: "number" },
        },
      },
    },
    assessmentScript: {
      type: "object",
      additionalProperties: false,
      required: [
        "minutes0to2",
        "minutes2to6",
        "minutes6to10",
        "minutes10to13",
        "minutes13to15",
      ],
      properties: {
        minutes0to2: { type: "string" },
        minutes2to6: { type: "string" },
        minutes6to10: { type: "string" },
        minutes10to13: { type: "string" },
        minutes13to15: { type: "string" },
      },
    },
    playbook: { type: "array", items: { type: "string" }, minItems: 10, maxItems: 10 },
    nicheAdvice: { type: "string" },
  },
} as const;
